name: PowerShell Gallery

on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 # Fetch all history for GitVersion

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Publish PowerShell Module
        shell: pwsh
        env:
          PS_GALLERY_API_KEY: ${{ secrets.PS_GALLERY_API_KEY }}
        run: |
          $module = "src/WvdDsc"
          $moduleManifest = Join-Path -Path $module -ChildPath WvdDsc.psd1
          (Get-Content -Path $moduleManifest) -replace "{{version}}", "${{ steps.gitversion.outputs.semVer }}" | Set-Content -Path $moduleManifest
          Publish-Module -Path $module -Repository PSGallery -NuGetApiKey "$env:PS_GALLERY_API_KEY"
